# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: contact-app-deployment
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: contact-app
#   template:
#     metadata:
#       labels:
#         app: contact-app
#     spec:
#       containers:
#       - name: contact-app
#         image: khushiappannavar/contact-app:v1
#         ports:
#         - containerPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contact-app
  template:
    metadata:
      labels:
        app: contact-app
    spec:
      containers:
      - name: contact-app
        image: khushiappannavar/contact-app:latest
        ports:
        - containerPort: 80
