apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: contact-app-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contact-app-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50